name: CI

on:
  # Trigger when code is pushed to main
  push:
    branches: [ main ]

  # Trigger when a PR targets main (open, sync, reopen)
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: security-devops-action
        uses: microsoft/security-devops-action@v1.12.0
        #with:
          # Deprecated, do not use.
          #command: # optional
          # A file path to a .gdnconfig file.
          #config: # optional
          # The name of the well known policy to use. Defaults to GitHub.
          #policy: # optional, default is GitHub
          # A comma separated list of analyzer categories to run. Values secrets, code, artifacts, IaC, containers. Example IaC,secrets. Defaults to all.
          #categories: # optional
          # A comma separated list of languages to analyze. Example javascript, typescript. Defaults to all.
          #languages: # optional
          # A comma separated list of analyzer to run. Example bandit, binskim, container-mapping, eslint, templateanalyzer, terrascan, trivy.
          #tools: # optional
          # Deprecated
          #includeTools: # optional
          # A SARIF filename that already exists. If it does, then the normal run will not take place and the file will instead be uploaded to MSDO backend.
          #existingFilename: # optional

      - name: AppSec Scanner
        # You may pin to the exact commit or the version.
        # uses: NirAlon/appsec_scan@8e1acc918cb521e8cfe7b7350b836547ac2b21ab
        uses: NirAlon/appsec_scan@latest





          
