name: CI

on:
  # Trigger when code is pushed to main
  push:
    branches: [ main ]

  # Trigger when a PR targets main (open, sync, reopen)
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: security-devops-action
        uses: microsoft/security-devops-action@v1.12.0
        with:
          # Deprecated, do not use.
          #command: # optional
          # A file path to a .gdnconfig file.
          #config: # optional
          # The name of the well known policy to use. Defaults to GitHub.
          #policy: # optional, default is GitHub
          # A comma separated list of analyzer categories to run. Values secrets, code, artifacts, IaC, containers. Example IaC,secrets. Defaults to all.
          #categories: # optional
          # A comma separated list of languages to analyze. Example javascript, typescript. Defaults to all.
          #languages: # optional
          # A comma separated list of analyzer to run. Example bandit, binskim, container-mapping, eslint, templateanalyzer, terrascan, trivy.
          tools: Checkov
          # Deprecated
          #includeTools: # optional
          # A SARIF filename that already exists. If it does, then the normal run will not take place and the file will instead be uploaded to MSDO backend.
          #existingFilename: # optional
        continue-on-error: true

          
      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      - name: AppSec Scanner
        # You may pin to the exact commit or the version.
        # uses: NirAlon/appsec_scan@8e1acc918cb521e8cfe7b7350b836547ac2b21ab
        uses: NirAlon/appsec_scan@latest
        continue-on-error: true

      - name: Aqua Security Trivy
        # You may pin to the exact commit or the version.
        # uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4
        uses: aquasecurity/trivy-action@0.32.0
        with:
          # Scan type to use for scanning vulnerability
          scan-type: fs
        continue-on-error: true

      - name: KICS Github Action
        # You may pin to the exact commit or the version.
        # uses: Checkmarx/kics-github-action@3545b741daf8fc816b081261995184aa12a247c0
        uses: Checkmarx/kics-github-action@v2.1.11
        with:
          output_path: results-dir
          platform_type: terraform
          output_formats: 'json,sarif'
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results-dir/results.sarif
